# reference: https://github.com/openai/codex/blob/main/docs/config.md
model = "gpt-5.4"
model_verbosity = "medium"
sandbox_mode = "workspace-write"
approval_policy = "never"

# 何の設定か分からないので保留
# file_opener = "cursor" # or vscode
notify = ["bash","-lc","afplay /System/Library/Sounds/Ping.aiff"]
model_reasoning_effort = "medium"
personality = "pragmatic"
service_tier = "fast"

[sandbox_workspace_write]
network_access = true

[tui]
notifications = ["agent-turn-complete","approval-requested"]
status_line = ["model-with-reasoning", "git-branch", "context-remaining", "five-hour-limit", "weekly-limit"]

[shell_environment_policy]
inherit = "core"

##############################
# MCPサーバの設定
##############################
experimental_use_rmcp_client = true

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"
"gpt-5.2-codex" = "gpt-5.3-codex"
"gpt-5.3-codex" = "gpt-5.4"
