# reference: https://github.com/openai/codex/blob/main/docs/config.md
model = "gpt-5.5"
model_verbosity = "medium"
sandbox_mode = "workspace-write"
approval_policy = "never"

# 何の設定か分からないので保留
# file_opener = "cursor" # or vscode
notify = ["bash","-lc","afplay /System/Library/Sounds/Ping.aiff"]
model_reasoning_effort = "xhigh"
personality = "pragmatic"

[sandbox_workspace_write]
network_access = true

[tui]
notifications = ["agent-turn-complete","approval-requested"]
status_line = ["model-with-reasoning", "git-branch", "context-remaining", "five-hour-limit", "weekly-limit", "fast-mode"]

[tui.model_availability_nux]
"gpt-5.5" = 4

[shell_environment_policy]
inherit = "core"

##############################
# MCPサーバの設定
##############################
experimental_use_rmcp_client = true

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true
fast_default_opt_out = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"
"gpt-5.2-codex" = "gpt-5.3-codex"
"gpt-5.3-codex" = "gpt-5.4"

[projects."/Users/takashabe/dev/src/github.com/CastingONE/castingone"]
trust_level = "trusted"

[projects."/Users/takashabe/dotfiles"]
trust_level = "trusted"

[projects."/Users/takashabe/dev/src/github.com/CastingONE/sandbox"]
trust_level = "trusted"

[plugins."github@openai-curated"]
enabled = true

[hooks.state]

[hooks.state."/Users/takashabe/.codex/hooks.json:post_tool_use:0:0"]
trusted_hash = "sha256:ff5f388525b989bc93457d57b8e1d9b72eb500db6d3266b9f131fcc04e9a7f49"

[hooks.state."/Users/takashabe/.codex/hooks.json:session_start:0:0"]
trusted_hash = "sha256:d6a30cd52fbfa63a852f7c4c125e8e1fc776c150787b9bbd0c30de587a999ab4"

[hooks.state."/Users/takashabe/.codex/hooks.json:user_prompt_submit:0:0"]
trusted_hash = "sha256:bb7dab1782aeea7e280e688e624a929f936b443f81061540c8907e1162f0e0fd"

[hooks.state."/Users/takashabe/.codex/hooks.json:stop:0:0"]
trusted_hash = "sha256:bb3e98a2e28bda26845eadd315e3003b40210803f405847d46fbe2a071b59824"
