import = [
   "/Users/takashabe/.config/alacritty/themes/catppuccin-mocha.toml",
   "/Users/takashabe/.config/alacritty/darwin/font.toml",
   "/Users/takashabe/.config/alacritty/darwin/keybinding.toml",
   "/Users/takashabe/.config/alacritty/darwin/shell.toml",
]

[cursor]
style = "Block"

[env]
TERM = "alacritty"

[mouse]
hide_when_typing = true

[window]
decorations = "none"
opacity = 1.0

[window.padding]
x = 2
y = 2
