[font]
### sfmono-square
# https://github.com/delphinus/homebrew-sfmono-square/tree/v1.2.2
# size = 20.0
# # size = 32.0
# [font.bold]
# family = "SF Mono Square"
# style = "Bold"
# [font.italic]
# family = "SF Mono Square"
# style = "Italic"
# [font.normal]
# family = "SF Mono Square"
# style = "Regular"

### pending-mono
# https://github.com/yuru7/pending-mono
# size = 17.0
# # size = 28.0
# [font.bold]
# family = "Pending Mono NF"
# style = "Bold"
# [font.italic]
# family = "Pending Mono NF"
# style = "Italic"
# [font.normal]
# family = "Pending Mono NF"
# style = "Regular"

### udev-gothic
# https://github.com/yuru7/udev-gothic
size = 18.0
# size = 28.0
[font.bold]
family = "UDEV Gothic 35NF"
style = "Bold"
[font.italic]
family = "UDEV Gothic 35NF"
style = "Italic"
[font.normal]
family = "UDEV Gothic 35NF"
style = "Regular"
