# Using python for running the tests, using `cram` test framework.
language: python

# Python version to run tests with.
python:
  - "2.7"

before_script:

  # Show the git version being used to test.
  - "git --version"

  # Install zsh.
  - "sudo apt-get install zsh"

  # Test config for git.
  - "git config --global user.name test"
  - "git config --global user.email test@test.test"

# Install python requirements.
install: "pip install -r requirements.txt --use-mirrors"

# Run the tests.
script: "make tests"
