[font]
size = 19.0
# size = 32.0

[font.bold]
family = "SF Mono Square"
style = "Bold"

[font.italic]
family = "SF Mono Square"
style = "Italic"

[font.normal]
family = "SF Mono Square"
style = "Regular"
