linters:
  disable-all: true
  # see. https://golangci-lint.run/usage/linters/
  enable:
    # default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # security
    - gosec
