# ==========================================================
# unite
# ==========================================================

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
" for vimfiler
if !has('nvim')
  source ~/.config/nvim/plugins/unite.rc.vim
endif
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
if = "has('nvim')"
hook_add = '''
source ~/.config/nvim/plugins/denite.rc.nvim
'''
hook_post_source = '''
source ~/.config/nvim/plugins/denite.rc.lazy.nvim
'''

[[plugins]]
repo = 'nixprime/cpsm'
build = 'env PY3=ON ./install.sh'

# ==========================================================
# auto completion
# ==========================================================

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
if = "has('nvim')"
hook_source = '''
source ~/.config/nvim/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
if = "has('lua')"
hook_source = '''
source ~/.config/nvim/plugins/neocomplete.rc.vim
'''

[[plugins]]
repo = 'zchee/deoplete-go'
depends = 'deoplete.nvim'
if = "has('nvim')"
on_ft = 'go'
build = 'make'
hook_source = '''
source ~/.config/nvim/plugins/deoplete-go.rc.vim
'''

[[plugins]]
repo = 'ujihisa/neco-look'
on_source = ['neocomplete.vim', 'deoplete.nvim']

# ==========================================================
# lang
# ==========================================================

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = ['vim', 'nvim']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'keith/tmux.vim'
on_ft = 'tmux'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go', 'tmpl']
hook_source = '''
source ~/.config/nvim/plugins/vim-go.rc.vim
'''

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'dag/vim-fish'
on_ft = 'fish'

[[plugins]]
repo = 'rhysd/vim-gfm-syntax'
on_ft = ['markdown', 'mkd']
