[[plugins]]
repo = 'Shougo/dein.vim'

# ==========================================================
# color
# ==========================================================

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
source ~/.config/nvim/plugins/onedark.rc.vim
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
source ~/.config/nvim/plugins/lightline.rc.vim
'''

# ==========================================================
# basic
# ==========================================================

[[plugins]] # コメント切り替え
repo = 'scrooloose/nerdcommenter'
hook_add = '''
source ~/.config/nvim/plugins/nerdcommenter.rc.vim
'''

[[plugins]] # taglist
repo = 'majutsushi/tagbar'
hook_add = '''
source ~/.config/nvim/plugins/tagbar.rc.vim
'''

[[plugins]] # 文字エンコード
repo = 'banyan/recognize_charcode.vim'
if = "!has('nvim')"

[[plugins]] # 括弧入力補完
repo = 'cohama/lexima.vim'

[[plugins]] # 整形
repo = 'junegunn/vim-easy-align'
hook_add = '''
source ~/.config/nvim/plugins/vim-easy-align.rc.vim
'''
# READMEのgifが分かりやすい. https://github.com/junegunn/vim-easy-align

[[plugins]] # 自動lint
repo = 'neomake/neomake'
if = "has('nvim')"
hook_add = '''
source ~/.config/nvim/plugins/neomake.rc.vim
'''

[[plugins]] # text object 拡張
repo = 'kana/vim-operator-user'

[[plugins]] # text object 拡張
repo = 'rhysd/vim-operator-surround'

[[plugins]] # sneak case <> camel case
repo = 'tyru/operator-camelize.vim'
hook_add = '''
source ~/.config/nvim/plugins/operator-camelize.rc.vim
'''

# ==========================================================
# filer
# ==========================================================

[[plugins]] # unite, deniteのfile_mruエンジン
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
hook_add = '''
source ~/.config/nvim/plugins/vimfiler.rc.vim
'''

[[plugins]] # matcher library for the denite
repo = 'nixprime/cpsm'
build = 'env PY3=ON ./install.sh'

# ==========================================================
# terminal
# ==========================================================

[[plugins]]
repo = 'Shougo/vimshell.vim'
depends = 'vimproc.vim'
if = "!has('nvim')"

[[plugins]]
repo = 'Shougo/vimproc.vim'
if = "!has('nvim')"
build = 'make'
