# ==========================================================
# unite
# ==========================================================

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
" for vimfiler
if !has('nvim')
  source ~/.config/nvim/plugins/unite.rc.vim
endif
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
if = "has('nvim')"
hook_add = '''
source ~/.config/nvim/plugins/denite.rc.nvim
'''
hook_post_source = '''
source ~/.config/nvim/plugins/denite.rc.lazy.nvim
'''

[[plugins]] # fast matcher
repo = 'nixprime/cpsm'
build = 'env PY3=ON ./install.sh'

[[plugins]] # denite source
repo = 'Shougo/neoyank.vim'

# ==========================================================
# auto completion
# ==========================================================

[[plugins]] # filetype判断
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
if = "has('nvim')"
hook_source = '''
source ~/.config/nvim/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
if = "has('lua')"
hook_source = '''
source ~/.config/nvim/plugins/neocomplete.rc.vim
'''

[[plugins]] # go補完エンジン
repo = 'zchee/deoplete-go'
depends = 'deoplete.nvim'
if = "has('nvim')"
on_ft = 'go'
build = 'make'
hook_source = '''
source ~/.config/nvim/plugins/deoplete-go.rc.vim
'''

[[plugins]] # 英単語補完
repo = 'ujihisa/neco-look'
on_source = ['neocomplete.vim', 'deoplete.nvim']

[[plugins]] # python補完
repo = 'zchee/deoplete-jedi'
depends = 'deoplete.nvim'
if = "has('nvim')"
on_ft = 'python'
hook_source = '''
source ~/.config/nvim/plugins/deoplete-jedi.rc.vim
'''

[[plugins]] # javascript タグジャンプとか
repo = 'ternjs/tern_for_vim'
if = "has('nvim')"
build = 'npm install'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]] # javascript補完
repo = 'carlitux/deoplete-ternjs'
depends = 'deoplete.nvim'
build = 'npm install -g tern'
if = "has('nvim')"
on_ft = ['javascript', 'javascript.jsx']
hook_source = '''
source ~/.config/nvim/plugins/deoplete-ternjs.rc.vim
'''

# ==========================================================
# lint, formatter
# ==========================================================

[[plugins]]
repo = 'prettier/vim-prettier'
on_ft = ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql']
do = 'npm install'
hook_source = '''
source ~/.config/nvim/plugins/vim-prettier.rc.vim
'''

[[plugins]]
repo = 'google/yapf'
on_ft = 'python'
rtp = 'plugins/vim'
hook_source = '''
source ~/.config/nvim/plugins/yapf.rc.vim
'''

# ==========================================================
# lang general
# ==========================================================

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = ['vim', 'nvim']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'keith/tmux.vim'
on_ft = 'tmux'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go', 'tmpl']
hook_source = '''
source ~/.config/nvim/plugins/vim-go.rc.vim
'''

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_source = '''
source ~/.config/nvim/plugins/jedi-vim.rc.vim
'''

[[plugins]]
repo = 'Glench/Vim-Jinja2-Syntax'
on_ft = 'jinja'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'dag/vim-fish'
on_ft = 'fish'

[[plugins]]
repo = 'rhysd/vim-gfm-syntax'
on_ft = ['markdown', 'mkd']

[[plugins]]
repo = 'billyvg/tigris.nvim'
on_ft = ['javascript', 'javascript.jsx']
build = './install.sh'
hook_source = '''
source ~/.config/nvim/plugins/tigris.rc.nvim
'''
